version: "3.5"
services:
  frontend:
    image: "nginx:latest"
    ports:
      - "9000:80"
    networks:
      - traefik-net
#    volumes:
#      - /var/log/docker:/var/log/docker
    container_name: "frontend"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.exampleapp.entrypoints=web,web-secure"
      - "traefik.http.routers.exampleapp.rule=Host(`example.yourdomainname.com.com`)"
#      - "traefik.http.routers.exampleapp.rule=Host(`test.yourdomainname.com.com`)" # requires wildcard certs for https. see redirecthttps entrypoint
#      - "traefik.http.routers.react-fe.rule=HostRegexp(`{hostname:^test*.*yourdomainname.com.com}`)" # requires wildcard certs for https. see redirecthttps entrypoint
      - "traefik.http.routers.exampleapp.middlewares=redirecthttps@file"
      - "traefik.http.routers.exampleapp.tls=true"
      - "traefik.http.routers.exampleapp.tls.certresolver=first" #maps to resolver in traefikv2.toml
      - "traefik.http.routers.exampleapp.service=frontend-example" # containername-profilename format

networks:
  traefik-net:
    external: true
  internal:
    external: false